language: ruby
rvm:
- 2.3.1
branches:
  only:
  - master
services:
- postgresql
before_script:
- psql -c 'create database quiettime_coordinator_test;' -U postgres
script: bundle exec rspec spec
env:
  global:
    secure: TzMx4rWkn+BoY3yb3YXAw33ynDEX5gunw6U9OG6qUEYayp/ZE6SMNj7mTYH+hbJISEHGnW0IA2OYs12TTPhkQ06+KoopodVQKTj9PaJKfJxSIcfhopkFJcwGaJDFpEmmYBbXdugnwd77nlmzMQhCIvZ4tFc2r5PrOcxcYZBsi7/pZfiXf33v3AZ4+YeSQI7rul5t4lmxua3q7sQus6LmAwmbWVHwlUg9QzBRyi63ixz3Tc9SRSud0ne6j9G8k4WDUga60DXOIT3ErJCmmFm/aq/cxJ/6bi4IgAnzG5pKS9M3c5Sj2VgcA0ot41wL8AmXDbE3tUTXhtErBYZ7+wzgest+Pfbfj7EF6pburbHNG1mtBRsQgt6Zw7C0V25hzAL6Igf++LwBhQc8cG3SUiOr7JDNm8WMZr0rNzPKlw8ZQlT3x7NKReLKXFzbDmNXmmtfL5PIVV8mn3TtInw/mnep1kgq7iHZAUrMqGHNHmFjieCBrZ/IfSfmA18pWiom0Qo5sfOd9l5GQA01ZIs28Zer0RZkeikbdmEz423Z655dSM5vj8ZBOGF52jQZo4F9D59J7WrKyS+rSGaU7KbR/dLoEEz6fjoREMeq0z5syYUM6EG+OCL3rH8eKPKa8kPD5xj6YdR63WEUZYowD/nWpmmmgPQRIawPSG6ePr/pOCLKG+M=
