language: ruby
rvm:
- 2.3.1
services:
- postgresql
before_script:
- psql -c 'create database quiettime_coordinator_test;' -U postgres
script: bundle exec rspec spec
env:
  global:
    secure: hM9+dhXi9mRyWQJh7moXpwKsSMp8WS/1tFIzrIMOelz4ra6utNR7Fo0OB6zxFglz7mR9VCUkAqKfrpcRuUbaBu+YTaHXAc5JprNXLNFf8r8sUoyH7cwJq0xbQQeSKHSz1HmBoOTi9iGkXOlUR+fOYS3zw12/InIa7IbtAFOnBJa8F6EuSz8CnqXf2pbUWKRd08vjYcYATY8kH5l2I9WszdlJ+wcS26QG8hm3Y2PQ2t9hHZVBPwu2FUJYXbC5SQJxBNsVSl8Qk0ozmUdWGWWCm7W37gVS0WK0LmdDkLCfbYRZNstNkCG3TIyUGHVTjKxQFWElBFcSKR3Iu+0dvB1szxTzVP5Ik5csoIn73cqbwm1j3Y45kXSlqEPLrP57VuJuCCcBxO1PtqyO9Ss1R16Xg+Q07Rk6ZuCMCSX4wgIuuGm9BOTClFyDCukMr0FyTye4io46Rh0KsQUzd62zSepo45gyG4QjZTlZaFo4BWWXbiAgexojvInU0XEvMEbeNgilTtXZULKKhtVsIK2M4R91tUlqoMq8qTmDm+MRItxEid+yQ7wPNO0FicrkkyOcPXQ6810VbIlmhTb4Z3X7ONNOt+W2kxglyRo1ObMD4qFr7QVzT4DEUzixe70HjsFMLu2c8d4bDjdVY3CiuBmLTjoFHZmhS4bJPPC1WH8AVkZLF6U=
