# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

keys: &keys
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  yelp_consumer_key: <%= ENV['YELP_CONSUMER_KEY'] %>
  yelp_consumer_secret: <%= ENV['YELP_CONSUMER_SECRET'] %>
  yelp_token: <%= ENV['YELP_TOKEN'] %>
  yelp_token_secret: <%= ENV['YELP_TOKEN_SECRET'] %>

development:
  <<: *keys
test:
  <<: *keys
production:
  <<: *keys

